name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    env:
      GOPRIVATE: github.com/zwiron/*

    steps:
      - uses: actions/checkout@v4

      - name: Configure private Go modules
        run: git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run linter
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.11.4

      - name: Run unit tests
        run: go test -race -count=1 -v -timeout 5m ./...
